language: ruby
cache: bundler
rvm:
  - 2.6.3
before_install:
- bundle install
- npm install
- npm install gulp-cli -g
- npm install github-release-notes -g
script:
- scripts/./submodule.sh
- gulp deploy
install: true
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  api_key: $GREN_GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
  script: scripts/./release.sh minor  
